### ISSUE TITLE
Bu(ó)g Anatoliego

### ISSUE THREAD

**Issue by mwdowski** [KGP2/KGP.TicketApp#25]
https://github.com/KGP2/KGP.TicketApp/blob/b5ee20e8763152e64b3f1fb5e26774f3a6371b0e/KGP.TicketApp.Backend/Controllers/UsersController.cs#LL89C35-L89C35

To chyba bug, o który chodzi Anatoliemu. Być może trzeba zrobić Request.Client.Host czy coś takiego, żeby dawać cookie stronce, która to wywołuje

@nobster14

**Comment by mwdowski** [comment]
chyba nie naprawiłem xD @nobster14

**Comment by nobster14** [comment]
Imo to powinno być tak, że jak anatoli chce sobie lokalnie testować aplikację to powinien lokalnie sobie zhostować serwer i wtedy sprawdzać działanie, wtedy to wszystko zadziała. @mwdowski @Tolisz
